### ISSUE TITLE
iOS 13 Features

### ISSUE THREAD

**Issue by holtwick** [holtwick/onepile#130]
- [x] PencilKit / iPad
- [x] OCR via OS / `VNRecognizeTextRequest` #35 
- [x] Support improved [Document Controller](https://developer.apple.com/wwdc19/719) to access NAS and USB #40 
- [x] Automatic dark mode detection #5 
- [x] [Document scanner](https://schiavo.me/2019/scanning-documents/) via OS #65 
- [x] Quicklook / Edit

Bugs:

- [x] Activating keyboard in note fails, does not get focus
- [x] Statusbar issues (dark/light)
- [x] Fix audio recorder
- [x] ~Framework7 update required~

**Comment by holtwick** [comment]
For Document Browser:

- [ ] 
- [ ] Give feedback if storage is supported e.g. by writing and reading a test file
- [ ] Fine tune NSFileCooordinator
- [ ] Trigger sync each 3 secs
- [ ] Support file/package renaming
- [ ] Remove all NSDocument related code
- [ ] Ask for a file name when creating new on in DocBrowser

**Comment by holtwick** [comment]
For F7/ProseMirrir/TipTap

- [ ] Editor focus is not working
- [ ] F7 v5 UI for info does not work
- [ ] F7 v5 does not look right in editor
- [ ] Avoid multiple click on button before action is fully performed
- [ ] Add UI for Quicklook functionality (Toolbar bottom?)

**Comment by holtwick** [comment]
Other features for this release:

- [ ] Bump to 2.0 #125 
- [ ] Implement public links #91 
- [ ] Add peers
- [ ] Check the share extension
- [ ] Add filtering and sorting / Sidebar?
