### ISSUE TITLE
Sync Issues

### ISSUE THREAD

**Issue by holtwick** [holtwick/onepile#89]
- [x] Sync is not triggered automatically on iOS
- [x] Deleted items are not synced #112 
- [ ] First Dropbox sync is slow #55 
- [x] Improve on Workspaces #98
